# Generated by Django 5.1.3 on 2024-12-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_eventrequest_status_alter_eventrequest_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
