# Generated by Django 5.1.3 on 2025-01-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_eventrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('transfer_method', models.CharField(default='online-payment', max_length=50)),
                ('receipt', models.CharField(max_length=3)),
                ('donation_purpose', models.TextField()),
                ('receipt_file', models.FileField(upload_to='donations/receipts/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
