# Generated by Django 5.1.2 on 2024-11-21 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_layer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventrequest',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_event_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
