# Generated by Django 5.1.3 on 2025-01-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_layer', '0005_donation_verified_alter_donation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('meeting_minutes', 'Meeting Minutes'), ('notice', 'Notice'), ('agenda', 'Agenda'), ('announcements', 'Announcements')], max_length=50),
        ),
    ]
